#!/bin/sh
#
# PROVIDE: xray
# REQUIRE: NETWORKING
# KEYWORD: shutdown
#
# Xray daemon

. /etc/rc.subr

name="xray"
rcvar=xray_enable

# 命令和参数
command="/home/admin/mysocks/xray"
command_args="-config /home/admin/mysocks/etc/config.json&"

# 用户和组
# root 默认即可，BSD rc.d 脚本可以用 setuid/setgid，但默认以 root 启动
# xray_user="nobody"
# xray_group="nogroup"

# 启动参数
start_precmd=""
stop_postcmd=""
pidfile="/var/run/${name}.pid"

# 启动时生效
load_rc_config $name
: ${xray_enable:="NO"}  # 默认不开启，可改成 YES

run_rc_command "$1"
