#!/bin/sh
#
# PROVIDE: tun_addr
# REQUIRE: tun2socks
# KEYWORD: shutdown

. /etc/rc.subr

name="tun_addr"
rcvar="${name}_enable"

start_cmd="${name}_start"
stop_cmd=":"

tun_addr_start()
{
    echo "Setting tun0 address..."
    if ifconfig tun0 >/dev/null 2>&1; then
        if ! ifconfig tun0 | grep -q "172.17.17.2"; then
            ifconfig tun0 add 172.17.17.2/30 && ifconfig tun0 inet6 add fd00:cd78:78::1
            echo "tun0 configured with 172.17.17.2/30"
        else
            echo "tun0 already configured"
        fi
    else
        echo "tun0 not found, waiting 2s..."
        sleep 2
	(ifconfig tun0 add 172.17.17.2/30 && ifconfig tun0 inet6 add fd00:cd78:78::1) || echo "Failed to configure tun0"
    fi
}

load_rc_config $name
run_rc_command "$1"
